### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by bestlem** [water-sucks/nixed#166]
Could you please put a license on this.,

I like this structure and with flake-parts as your base I can build my requirements on this.

However without a license no one else has permission to copy this without asking you. I think your README implies this is open source but possibly only the packages.

See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by water-sucks** [comment]
I really forgot about this, huh...I added a [license](https://github.com/water-sucks/nixed/commit/dda4eeedc43fee55981cfccebdcdda3cfbd1a9d4)  just now. Thanks for letting me know and for checking out my repo :}
