### ISSUE TITLE
You Mean the Oakland Raiders

### ISSUE THREAD

**Issue by Thomashighbaugh** [water-sucks/nixed#196]
Since they moved from my native East Bay to that sweltering hell hole in the desert, I have no been able to care about football (once I would go to games and shoulder check other teams fans, like a good native of the East Bay and graduate of a blighted bayshore high school GO FARMERS!) but those will always be the Oakland Raiders, which Jano you got listed here played exclusively for last I checked. Regardless, while Al Davis and the Chucky doll that is his son will never be forgiven, it will forever be true that the `Autumn wind is a Raider`

PS hilarious description for your repo, I feel it though bruh

**Comment by water-sucks** [comment]
Honestly this is hilarious; I totally agree. I'll change it to Oakland and add a footnote, for the haters. I wish they were still in Oakland;  I'm an East Bay native myself, still living in Fremont, so I feel it.

**Comment by water-sucks** [comment]
Fixed by [0d0a630](https://github.com/water-sucks/nixed/commit/0d0a630c93d558e9364d03ad0cf56045d46059a3).
